name: Build

on:
  push:
    paths:
      - 'setup.py'

jobs:
  build_wheels_and_upload:
    name: Build wheels and upload
    runs-on: ubuntu-20.04
    environment: pypi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: python -m pip install twine wheel
      - name: Build wheels
        run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*
      - name: Upload
        run: |
          python -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PSW }} dist/*
